version: '3.8'

services:
  database:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - app_net
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: on-failure
    container_name: nest_app
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  mysql_data:
